[about]
name = "è€„è€‹"
avatar = "https://imgs.qiubiaoqing.com/qiubiaoqing/imgs/681a46ece1cd1qft.jpeg"
hobbies = ["ğŸ± HA", "ğŸ§ LaoWu", "ğŸ¥˜ HA"]
skills = ["Linux", "Golang", "Rust", "TypeScript"]

[social]
github = ""
website = ""


